version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n34mwpdcdfpw"
s3_prefix = "hello-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
